version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6

    steps:
      - checkout

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - restore_cache:
          keys:
            - build-v1-{{ checksum "Gemfile.lock" }}
            - build-v1-

      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      - save_cache:
          key: build-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Jekyll Build
          command: bundle exec jekyll build

      - persist_to_workspace:
          root: _site
          paths:
            - ./*

  deploy:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "10:70:43:58:13:93:de:29:4f:e0:db:73:e4:2e:f4:42"

      - run:
          name: Install ghp-import
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install ghp-import

      - attach_workspace:
          at: _site

      - run:
          name: Deploy Site
          command: |
            . venv/bin/activate
            ghp-import _site -pm "[ci skip] $(git log --format=oneline -n 1 $CIRCLE_SHA1)"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
